# Generated by Django 3.2.5 on 2021-07-23 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='course',
        ),
    ]
