# Generated by Django 3.2.5 on 2021-07-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodleSiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdlSite', models.URLField(null=True)),
                ('mdlToken', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='mdl_user_id',
            field=models.IntegerField(default=False, null=True),
        ),
    ]
